# The URL the site will be built for
base_url = "https://recipes.arne.beer/"
#default_language = 'de'

title = "Unsere Rezepte"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
  { name = "authors", rss = true },
  { name = "tags", rss = true },
  { name = "duration", rss = true },
]

# Syntax highlighting configuration
[markdown.highlighting]
light_theme = "github-light"
dark_theme = "github-dark"

[extra]
# Put all your custom variables here
